docs/multi-node-deployment.md

Add automation instruction and with link to the ansible playbook repository

Add automation details

---

docs/etherboy-backend.md
docs/etherboy-game.md
docs/multi-node-deployment.md
docs/phaser-sdk-demo-websocket-web3.md
docs/phaser-sdk-demo-websocket.md
docs/phaser-sdk-demo.md
docs/prereqs-ubuntu.md
docs/prereqs.md
docs/simple-social-network-example.md

Updates with latest build

---

.gitignore
docs/prereqs-ubuntu.md
docs/prereqs.md
website/translated_docs/ja/prereqs-ubuntu.md
website/translated_docs/ja/prereqs.md
website/translated_docs/zh-CN/prereqs-ubuntu.md
website/translated_docs/zh-CN/prereqs.md

Updated the blueprint command from weave-blueprint repo, according to go-loom repo using call contract methods.

Blueprint go loom

---

website/package-lock.json
website/package.json

Change package.json to point to:
`"docusaurus": "github:facebook/docusaurus#pull/709/head",`
to fix translation issues in sidebar... 
(see https://github.com/facebook/Docusaurus/pull/709/files)

Change package.json to point to facebook/docusaurus#pull/709/head

---

website/package-lock.json
website/package.json

Docusarus dependency -> `git://github.com/gimdongwoo/docusaurus.git#metadata`

Change to point to original author of PR

---

docs/evm.md

Changes regarding deploy EVM contract returning txReceipt and new GetCode query.

Tx receipt get code

---

docs/prereqs-ubuntu.md
docs/prereqs.md

Fixes https://github.com/loomnetwork/loom-sdk-documentation/issues/81

Add dep install instructions

---

docs/unity-tuffle-loom-sample.md
website/i18n/en.json
website/sidebars.json
website/translated_docs/zh-CN/unity-truffle-loom-sample.md

- Now user can access the article from the side bar
- Also added the original post link since it's from others.

fix the unity quick start sidebar

---

docs/release-notes.md

* [EVM indexed filter](https://loomx.io/developers/docs/en/web3js-event-filters.html)
* EVM filter pool fixes
* Loom-JS EVM updates for indexed filters
* Loom-JS EVM fixes for getting block by hash

Release 285 - July 17th

---

docs/block-explorer-tutorial.md
docs/cocos-sdk-quickstart.md

- still translating the docs. Might find more errors, so you don't have to merge it now.

fix grammar error

---

docs/extdev-transfer-gateway.md

Get everyone to start from scratch to minimize potential issues.

Minor tweaks to Transfer Gateway Tutorial

---

docs/non-validator-node.md

* Updated [the documentation](https://loomx.io/developers/docs/en/non-validator-node.html) to point to the new dposv2 cluster.

Documentation: Updated the documentation to point to the dposv2 cluster.

---

docs/non-validator-node.md

Locked loom to version 560.

---

docs/join-test-net.md
website/translated_docs/ja/join-test-net.md
website/translated_docs/ko/join-test-net.md
website/translated_docs/zh-CN/join-test-net.md

fix image not showing in other language

---

docs/non-validator-node.md

* Updated the documentation to point to extdev-plasma-us1 instead of dpos.

Updated the documentation to point to extdev-plasma-us1 instead of dpos.

---

docs/transfer-gateway.md

fix broken links transfer-gateway.md

fix broken links transfer-gateway.md

---

scripts/get_loom.sh

bring back get_loom script

---

docs/.vuepress/config.js

adding page description to config.js

adding page description to config.js

---

docs/.vuepress/theme/components/SidebarGroup.vue
docs/.vuepress/theme/styles/palette.styl
docs/.vuepress/theme/styles/scroll.styl

New template

---

docs/en/testnet-plasma.md
docs/ja/testnet-plasma.md
docs/ko/testnet-plasma.md
docs/zh-CN/testnet-plasma.md

remove reference to faucet

---

docs/.vuepress/theme/components/DropdownLink.vue
docs/.vuepress/theme/components/Navbar.vue
docs/.vuepress/theme/styles/mobile.styl
docs/.vuepress/theme/styles/theme.styl

navbar width issue & highlighting issue fixed

---

docs/.vuepress/enhanceApp.js
docs/.vuepress/theme/Layout.vue
docs/.vuepress/theme/components/Navbar.vue
docs/.vuepress/theme/components/SearchBox.vue
docs/.vuepress/theme/components/Sidebar.vue
docs/.vuepress/theme/styles/theme.styl
package.json
yarn.lock

fixed iphone button click issue & dark mode issue

---

docs/en/simple-social-network-example.md
docs/en/testnet-plasma.md
docs/en/transfer-gateway-example.md
docs/en/transfer-gateway.md
docs/en/truffle-deploy.md
docs/en/unity-quick-start.md
docs/en/unity-sample-tiles-chain-evm.md
docs/en/unity-sdk-evm.md
docs/en/unity-sdk-overview.md
docs/en/unity-sdk-plugin.md
docs/en/unity-truffle-loom-sample.md
docs/en/validator.md
docs/en/web3js-event-filters.md
docs/en/web3js-loom-provider-truffle.md
docs/en/what-are-dappchains.md

sanitize and and review p3

---

docs/.vuepress/config.js
docs/en/jump-start-extdev-plasma-us1.md
docs/en/jump-start-plasma.md

For launching extdev-plasma-us1 and plasma from jump start images

Add jump start documentation

---

docs/.vuepress/config.js
docs/en/deposit-and-withdraw-trx.md

add deposit and withdraw trx

---

docs/ja/multi-node-deployment.md
docs/ko/multi-node-deployment.md
docs/zh-CN/multi-node-deployment.md

* Add specific instruction to **not** copy the examples
* Added `DPOSVersion: 3` to `loom.yml`
The problem was caused by
```json
"power": 10,
```
Where quotes are needed in newer version of loom.
https://github.com/loomnetwork/loomchain/issues/1249

Update multi-node documentation

---

docs/en/basic-install-all.md

fix broken link

---

docs/en/basic-install-all.md

fix broken link staging

---

docs/ja/deposit-and-withdraw-trx.md
docs/ko/deposit-and-withdraw-trx.md
docs/zh-CN/deposit-and-withdraw-trx.md

add missing deposit and withdraw trx page

add missing deposit and withdraw trx page

---

docs/en/deploy-loom-mainnet.md
docs/ja/deploy-loom-mainnet.md
docs/ko/deploy-loom-mainnet.md
docs/zh-CN/deploy-loom-mainnet.md

fix readFileSync

---

docs/en/deploy-loom-mainnet.md
docs/ja/deploy-loom-mainnet.md
docs/ko/deploy-loom-mainnet.md
docs/zh-CN/deploy-loom-mainnet.md

update dev deployment

---

build_docs.sh
docs/en/top-erc20s.md
docs/ja/top-erc20s.md
docs/ko/top-erc20s.md
docs/zh-CN/top-erc20s.md

fix broken links in top erc20s list

fix broken links in top erc20s list

---

build_docs.sh

top erc20s - replace `.` with `*`

top erc20s - replace `.` with `*`

---

build_docs.sh

add .vuepress to path

---

docs/en/top-erc20s.md
docs/ja/top-erc20s.md
docs/ko/top-erc20s.md
docs/zh-CN/top-erc20s.md

add full path

---

docs/en/basic-install-all.md

add purpose chapter to setup local loom chain

add purpose chapter to setup local loom chain

---

docs/.vuepress/config.js
docs/en/dapp-metrics-website-info.md
docs/ja/dapp-metrics-website-info.md
docs/ko/dapp-metrics-website-info.md
docs/zh-CN/dapp-metrics-website-info.md

dapp metrics

---

docs/en/release-notes.md

Loom 2.0 Release Build 1213

---

docs/en/intro-to-loom.md

de-emphasize "What is the Loom SDK"

de-emphasize "What is the Loom SDK"

---

scripts/get_loom.sh

bring back get_loom.sh

---

docs/en/how-to-get-started.md

update universal signing tutorial

update universal signing tutorial

---

docs/en/multi-node-deployment.md
docs/ja/multi-node-deployment.md
docs/ja/non-validator-node.md
docs/ko/multi-node-deployment.md
docs/ko/non-validator-node.md
docs/zh-CN/multi-node-deployment.md
docs/zh-CN/non-validator-node.md

Replace RPCListenAddress with RPCBindAddress
GitHub issue: https://github.com/loomnetwork/loom-sdk-documentation/issues/319
`loom.yaml` is updated but I found a few occurrences in the Chinese, Japanese, and Korean versions of the `non-validator-node` page.
BTW, these pages are outdated.

Replace RPCListenAddress with RPCBindAddress

---

docs/en/release-notes.md

Loom 2.0 Release Build 1263

---

docs/en/mainnet-plasma.md
docs/en/testnet-plasma.md

update mainnet-plasma and testnet-plasma

update mainnet-plasma and testnet-plasma

---

docs/en/dapp-metrics-website-info.md
docs/ja/dapp-metrics-website-info.md
docs/ko/dapp-metrics-website-info.md
docs/zh-CN/dapp-metrics-website-info.md

Adds Alice IFO smart contract

---

docs/.vuepress/config.js
docs/en/relentless.md
docs/ja/relentless.md
docs/ko/relentless.md
docs/zh-CN/relentless.md

How to Set-up Relentless

---

docs/en/relentless.md
docs/ja/relentless.md
docs/ko/relentless.md
docs/zh-CN/relentless.md

- updated the name of the Relentless repo
- removed the Update the Card Data section. I'll add it later, once we figure out the best way to do it.

Update how to set up Relentless

---

docs/.vuepress/config.js
docs/en/arch.md
docs/en/basechain-release-notes.md
docs/en/extdev-release-notes.md
docs/en/release-notes.md
docs/ja/basechain-release-notes.md
docs/ja/extdev-release-notes.md
docs/ko/basechain-release-notes.md
docs/ko/extdev-release-notes.md
docs/zh-CN/basechain-release-notes.md
docs/zh-CN/extdev-release-notes.md

basechain and extdev release notes

basechain and extdev release notes

---

docs/en/jump-start-extdev-plasma-us1.md
docs/en/jump-start-plasma.md
docs/ja/jump-start-extdev-plasma-us1.md
docs/ja/jump-start-plasma.md
docs/ko/jump-start-extdev-plasma-us1.md
docs/ko/jump-start-plasma.md
docs/zh-CN/jump-start-extdev-plasma-us1.md
docs/zh-CN/jump-start-plasma.md

update jump start pages

---

docs/.vuepress/locales/en.json
docs/.vuepress/locales/ja.json
docs/.vuepress/locales/ko.json
docs/.vuepress/locales/zh-CN.json
docs/.vuepress/theme/components/Page.vue
docs/.vuepress/theme/styles/scroll.styl

- fixed #200 the sidebar scroll issue
- fixed #302 add a telegram link at the bottom of every page

add TG link

---

docs/en/transfer-gateway.md

Removes reference to outdated repo

Removes reference to outdated repo

---

docs/en/deploy-loom-mainnet.md
docs/ja/deploy-loom-mainnet.md
docs/ko/deploy-loom-mainnet.md
docs/zh-CN/deploy-loom-mainnet.md

fix yearly fee

---

docs/en/testnet-plasma.md
docs/ja/testnet-plasma.md
docs/ko/testnet-plasma.md
docs/zh-CN/testnet-plasma.md

Update extdev warning

---

docs/en/jump-start-plasma.md
docs/ja/jump-start-plasma.md
docs/ko/jump-start-plasma.md
docs/zh-CN/jump-start-plasma.md

1. Match the manual run command with the startup script
1. Set to nv0, nv1, nv2

Update basechain peers

---

docs/.vuepress/config.js
docs/en/jump-start-extdev-plasma-us1.md
docs/en/jump-start-plasma.md

Add the HW requirements for running a node

Add the HW requirements for running a node

---

docs/en/basechain-release-notes.md
docs/ja/basechain-release-notes.md
docs/ko/basechain-release-notes.md
docs/zh-CN/basechain-release-notes.md

Add upgrade instructions for 1346

Add upgrade instructions for 1346

---

docs/en/withdrawing-and-claiming-rewards.md
docs/ja/withdrawing-and-claiming-rewards.md
docs/ko/withdrawing-and-claiming-rewards.md
docs/zh-CN/withdrawing-and-claiming-rewards.md

This command was renamed over 9 months ago.

Rename withdraw-rewards command to withdraw-funds

---

docs/en/basic-install-all.md
docs/en/basic-install-osx.md
docs/ja/basic-install-all.md
docs/ja/basic-install-osx.md
docs/ko/basic-install-all.md
docs/ko/basic-install-osx.md
docs/zh-CN/basic-install-all.md
docs/zh-CN/basic-install-osx.md
scripts/get_loom.sh

For https://github.com/loomnetwork/loom-sdk-documentation/issues/386

Update download location in script

---

docs/en/relentless.md

fixed the protoc link

---

docs/.vuepress/public/json/topTokensList.json
docs/en/top-erc20s.md
docs/ja/top-erc20s.md
docs/ko/top-erc20s.md
docs/zh-CN/top-erc20s.md

Remove LOOM from top token list

Remove LOOM from top token list

---

docs/.vuepress/public/json/topTokensList.json
docs/en/top-erc20s.md
docs/ja/top-erc20s.md
docs/ko/top-erc20s.md
docs/zh-CN/top-erc20s.md

Add DAI v2

---

build_docs.sh

like this: https://loomx.io/developers/docs/en/
this will fix the #225

remove old sdk doc files

---

docs/en/mainnet-plasma.md
docs/en/testnet-plasma.md
docs/ja/mainnet-plasma.md
docs/ja/testnet-plasma.md
docs/ko/mainnet-plasma.md
docs/ko/testnet-plasma.md
docs/zh-CN/mainnet-plasma.md
docs/zh-CN/testnet-plasma.md

Update max gas limit per tx
